name: Dependabot Auto Merge

on: [pull_request]

jobs:
  automerge:
    name: Dependabot Auto Merge
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
