name: Dependabot Auto Merge

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  test:
    name: Auto-merge minor and patch updates
    runs-on: ubuntu-latest
    steps:
      - uses: koj-co/dependabot-pr-action@v1.1.12
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-minor: true
          merge-patch: true
