name: Release workflow

on:
  release:
    types: [created]

jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/codebench
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            rg.fr-par.scw.cloud/codebench/api:${{ steps.get_tag.outputs.tag }}
            rg.fr-par.scw.cloud/codebench/api:latest
      - name: Deploy on Porter
        run: curl -X POST "https://dashboard.getporter.dev/api/webhooks/deploy/${{secrets.PORTER_WEBHOOK}}?commit=${{ steps.get_tag.outputs.tag }}"
